Updating README, doing some formatting, adding workflow for mei2cff

diff --git a/workflows/mei-citation-file-format-extraction.yml b/workflows/mei-citation-file-format-extraction.yml
--- a/workflows/mei-citation-file-format-extraction.yml
+++ b/workflows/mei-citation-file-format-extraction.yml
@@ -1,4 +1,4 @@
-name: Extraction of Dublin Core Metadata from MEI Files
+name: Extraction of Citation File Format Metadata from MEI Files
 
 on:
   push:
@@ -12,7 +12,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  extract-dublin-core:
+  extract-citation-file-format:
     runs-on: ubuntu-latest
 
     steps:
@@ -31,8 +31,8 @@ jobs:
       - name: Create necessary directories
         run: |
           mkdir -p .github/workflow-reports
-          mkdir -p metadata/dc
-          echo "OUTPUT_DIR=$(pwd)/metadata/dc" >> $GITHUB_ENV
+          mkdir -p metadata/cff
+          echo "OUTPUT_DIR=$(pwd)/metadata/cff" >> $GITHUB_ENV
 
       - name: Install Java and Saxon-HE
         run: |
@@ -56,9 +56,9 @@ jobs:
           echo "Java Version:"
           java -version
 
-      - name: Find all XML files and extract Dublin Core metadata
+      - name: Find all XML files and extract Citation File Format metadata
         env:
-          REPORT_FILE: ".github/workflow-reports/mei-dublin-core-extraction.md"
+          REPORT_FILE: ".github/workflow-reports/mei-citation-file-format-extraction.md"
         run: |
           REPORT="$REPORT_FILE"
 
@@ -70,31 +70,28 @@ jobs:
             > xml_files.txt
 
           # write date and time to report
-          echo "Dublin Core metadata extraction started at $(date)" >> "$REPORT"
+          echo "Citation File Format metadata extraction started at $(date)" >> "$REPORT"
           echo "Found $(wc -l < xml_files.txt) XML files to process." >> "$REPORT"
 
+          # prepare file list for XSLT processing
+          input_files=""
           while IFS= read -r file; do
-
-            java -jar "$SAXON_JAR" -o:"$OUTPUT_DIR/$(basename "$file" .xml)-dc.xml" -s:"$file" -xsl:"$(pwd)/mei-metadata-toolkit/src/xsl/mei2dc.xsl"
-
-            output_file="$OUTPUT_DIR/$(basename "$file" .xml)-dc.xml"
-
-            if [ -f "$output_file" ]; then
-              if grep -q "<oai_dc:dc" "$output_file"; then
-                echo "Dublin Core metadata extracted successfully to $output_file" >> "$REPORT"
-              else
-                echo "No Dublin Core metadata found in $file." >> "$REPORT"
-                rm "$output_file"
-              fi
-            else
-              echo "Failed to create output file for $file" >> "$REPORT"
-            fi
-
-            echo "" >> "$REPORT"
-            
+            input_files="$input_files $file"
           done < xml_files.txt
+          echo "INPUT_FILES=$input_files" >> $GITHUB_ENV
 
-          echo "Dublin Core extraction completed. Extracted metadata files are located in $OUTPUT_DIR." >> "$REPORT"
+          # run XSLT transformation to extract CFF metadata and provide input files as parameter
+          java -jar "$SAXON_JAR" -o:"$OUTPUT_DIR/CITATION.cff" -s:"$input_files" -xsl:"$(pwd)/mei-metadata-toolkit/src/xsl/mei2cff.xsl" -param input-files "'$input_files'"
+          
+          output_file="$OUTPUT_DIR/CITATION.cff"
+
+          if [ -f "$output_file" ]; then
+              echo "Citation File Format metadata extracted successfully to $output_file" >> "$REPORT"
+          else
+            echo "Failed to create output file for $file" >> "$REPORT"
+          fi
+
+          echo "" >> "$REPORT"
 
           cat "$REPORT"
 
@@ -103,17 +100,17 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: dublin-core-extraction-report
-          path: .github/workflow-reports/mei-dublin-core-extraction.md
+          name: citation-file-format-extraction-report
+          path: .github/workflow-reports/mei-citation-file-format-extraction.md
 
 
       - name: Commit and Push
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
-          git add .github/workflow-reports/mei-dublin-core-extraction.md
-          git add metadata/dc/*.xml
-          git commit -m "Update Dublin Core extraction report" || echo "No changes to commit"
+          git add .github/workflow-reports/mei-citation-file-format-extraction.md
+          git add metadata/cff/CITATION.cff
+          git commit -m "Update Citation File Format extraction report" || echo "No changes to commit"
           git push
           # Note: The 'git push' step will fail in Pull Request workflows unless you use a specific token
         
